version: '3'

services:
  app:
    container_name: rate-limiter
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/.env
    networks:
      - rate-limiter

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    restart: always
    networks:
      - rate-limiter

networks:
  rate-limiter:
    name: rate-limiter
    driver: bridge